const categoryKR = {
    // 대분류
    top: "top",
    bottom: "bottom",
    underwear: "underwear",
    acc: "acc",
    kids: "kids",
    swimwear: "swimwear",
    skirts_dress: "skirts_dress",

    sleeveless: "sleeveless",
    long: "long",
    short: "short",
    shorts: "shorts",
    items: "items",
    jewelry: "jewelry",
    bikini: "bikini",
    one_pice: "one_pice",
    skirts: "skirts",

    t_shirts: "t_shirts",
    outer: "outer",
    sweatshirts: "sweatshirts",
    shirts: "shirts",
    zip_ups: "zip_ups",
    knitwear: "knitwear",
    bra: "bra",
    sleepwear: "sleepwear",
    panties: "panties",
    socks: "socks",
    hairband: "hairband",
    hairpin: "hairpin",
    umbrella: "umbrella",
    belt: "belt",
    shoes: "shoes",
    sunglasses: "sunglasses",
    gloves: "gloves",
    hats: "hats",
    earring: "earring",
    bags: "bags",
    leggings: "leggings",
    jogger: "jogger",
    cotton: "cotton",
    training: "training",
    cargo: "cargo",
    jeans: "jeans",
    slacks: "slacks",
    jumpsuit: "jumpsuit",
    mini_skirts: "mini_skirts",

    graphic: "graphic",
    striped: "striped",
    solid: "solid",
    checkered: "checkered",
    dott: "dot",
    pattern: "pattern",

    //성별
    f: "여성",
    m: "남성",
    u: "공용",

    // 아동
    kids: "아동",

    // 색상
    black: "블랙",
    white: "화이트",
    gray: "그레이",
    navy: "네이비",
    blue: "블루",
    sky_blue: "스카이블루",
    beige: "베이지",
    brown: "브라운",
    ivory: "아이보리",
    khaki: "카키",
    green: "그린",
    mint: "민트",
    yellow: "옐로우",
    orange: "오렌지",
    red: "레드",
    wine: "와인",
    pink: "핑크",
    purple: "퍼플",
    charcoal: "차콜",
    cream: "크림",

};

export default categoryKR;
